apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/app: mysql
    app.kubernetes.io/name: mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: mysql
      app.kubernetes.io/name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: mysql
        app.kubernetes.io/name: mysql
    spec:
      serviceAccountName: clo
      containers:
      - name: mysql
        image: mysql
        volumeMounts:
        - mountPath: /data/db
          name: vol-mysql
        ports:
        - containerPort: 3306
        env:
        - name: DB_User
          valueFrom:
            secretKeyRef:
              name: grp10-secret
              key: DB_User
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grp10-secret
              key: DB_Password
      volumes:
        - name: vol-mysql
          persistentVolumeClaim:
            claimName: grp10-pvc